# Generated by Django 5.2.8 on 2025-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productname', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('productbrand', models.CharField(max_length=20)),
                ('Dateofpack', models.DateField()),
                ('Dateofdeli', models.DateField()),
                ('price', models.IntegerField()),
                ('productID', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
    ]
